Option Compare Database
Option Explicit

' *************************************************************************************
' マスタ・管理ファイル取込み
' *************************************************************************************

Public Function マスタ取込み()

    Call PutLog("マスタ取込み()", "start")
    
    '//SQL CEWEB
    Call PutLog("マスタ取込み()", "CEWEBのマスタテーブルを更新")
    Call V_SQL部門更新
    Call V_SQL作業担当更新
    Call V_SQL顧客更新
      
    '//Mテーブル・Dテーブル
    Call PutLog("マスタ取込み()", "SUPPORTDBのマスタテーブルを更新")
    Call V_マスタ取込("M_商品", "M_商品")
    Call V_マスタ取込("M_対応区分", "M_対応区分")
    Call V_マスタ取込("M_対応内容項目", "M_対応内容項目")
    Call V_マスタ取込("M_定型文", "M_定型文")

    Call PutLog("マスタ取込み()", "end")

End Function