USE [SUPPORTDB]
GO

/****** Object:  Table [dbo].[SQL_部門]    Script Date: 2025/12/04 16:09:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SQL_部門](
	[部門コード] [bigint] NOT NULL,
	[部門名] [nvarchar](255) NULL,
	[更新日] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[部門コード] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

